_start:
    pattern:  /
    defaults: { _controller: AcmeIndexBundle:Index:index }

_showPost:
    pattern: /show/{id}
    defaults: { _controller: AcmeIndexBundle:Index:Show }

profile:
    resource: "@AcmeUserBundle/Controller/IndexController.php"
    type: annotation
    prefix: /profile