_start:
    pattern:  /
    defaults: { _controller: AcmeIndexBundle:Index:index }

_userform:
    pattern: /userform/
    defaults: { _controller: AcmeIndexBundle:Index:Form }

profile:
    resource: "@AcmeUserBundle/Controller/IndexController.php"
    type: annotation
    prefix: /profile