_start:
    pattern:  /
    defaults: { _controller: AcmeIndexBundle:Index:index }

_userform:
    pattern: /userform/
    defaults: { _controller: AcmeIndexBundle:Index:Form }

profile:
    pattern: /profile/
    defaults: { _controller: AcmeUserBundle:Index:index }